debug: true

info:
  id: ${spring.application.name}

server:
  port: ${PORT:0}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411
  rabbitmq:
      addresses: ${vcap.services.reservations-rabbitmq.credentials.uri}
      host: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8080
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/