info:
  id: ${spring.application.name}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411

### Docker Properties Start ###
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    virtual-host-name: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
### Docker Properties End ###