spring:
  profiles.active: default
---
spring:
  profiles: default
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411

info:
  id: ${spring.application.name}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    virtual-host-name: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
---
spring:
   profiles: docker
   jpa:
       generate-ddl: true
     sleuth:
       sampler:
         percentage: 1.0
       log:
         json:
           enabled: true
     zipkin:
       host: zipkin-service
       base-url: http://zipkin-service:9411

info:
 id: ${spring.application.name}

endpoints:
 restart:
   enabled: true
 shutdown:
   enabled: true
 health:
   sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    virtual-host-name: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10