#debug: true
#
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework: DEBUG

info:
  id: ${spring.application.name}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  profiles:
    active: default

---

spring:
  profiles: default
  jpa:
   generate-ddl: true
  sleuth:
   sampler:
     percentage: 1.0
   log:
     json:
       enabled: true
  zipkin:
    enabled: true
    host: zipkin
#    base-url: http://localhost:9411/

eureka:
  instance:
    virtual-host-name: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    hostname: discovery
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
---

spring:
  profiles: dev
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/