#debug: true
#
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework: DEBUG

info:
  id: ${spring.application.name}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  client:
    name: ${spring.application.name}
  eureka:
    enabled: true

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
  profiles:
    active: default

---

spring:
  profiles: default
  jpa:
   generate-ddl: true
  sleuth:
   sampler:
     percentage: 1.0
   log:
     json:
       enabled: true
  zipkin:
    enabled: true
#    host: zipkin-service
    baseUrl: http://zipkin-service:9411/

eureka:
  instance:
    hostname: ${spring.application.name}
    appname: ${spring.application.name}
    virtual-host-name: ${spring.application.name}
    instanceId: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    nonSecurePortEnabled: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetchRegistry: true

---

spring:
  profiles: dev
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true