server:
  port: ${PORT:6000}
management.port: 9008

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    stream:
      bindings:
        output:
          destination: venuetopic
          content-type: application/json
          resetOffsets: true
  profiles:
    active: default

---

spring:
  profiles: docker
  couchbase:
    bucket:
      name: default
      password:
    env:
      ssl:
        enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

---

spring:
  profiles: default
  couchbase:
    bootstrap-hosts: 127.0.0.1
    bucket:
      name: venue
      password:
    env:
      ssl:
        enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
