server:
  port: ${PORT:8000}

message: Hello Ani!

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          group: reservations-group
          durableSubscription: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  instance:
    hostname: reservation-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true