server:
  port: ${PORT:8000}

message: Hello Ani!

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          group: reservations-group
          durableSubscription: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: reservation
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/