server:
  port: ${PORT:9999}

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: reservations

eureka:
  instance:
    hostname: reservation-client

#zuul:
#  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
#
#  routes:
#    reservation-service:
#        path: /reservations/**
#        serviceId: reservation-service
#        stripPrefix: false
#        sensitiveHeaders: