server:
  port: ${PORT:9411}

spring:
  datasource:
    initialize: false
  sleuth:
    enabled: false

zipkin:
  store:
    type: mem

### Docker Properties Start ###
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
#  instance:
#    virtual-host-name: ${spring.application.name}
#    leaseRenewalIntervalInSeconds: 10
### Docker Properties End ###