server:
  port: ${PORT:9411}

spring:
  datasource:
    initialize: false
  sleuth:
    enabled: false

zipkin:
  store:
    type: mem


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: zipkin
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/